Try to download and unzip assignment zips.

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -42,6 +42,54 @@ jobs:
           -H "Authorization: Bearer $GITHUB_TOKEN" \
           https://api.github.com/repos/cmsc430/assignments/actions/workflows/push.yml/dispatches \
           -d '{"ref":"main"}'
+    - name: Poll for zips
+      id: poll_workflow
+      env:
+        GITHUB_TOKEN: ${{ secrets.PAT_ZIPS_WORKFLOW }}
+      run: |
+          MAX_ATTEMPTS=5  # Maximum polling attempts (2 minutes each = 10 minutes)
+          ATTEMPT=0
+          STATUS="in_progress"
+          
+          while [[ "$ATTEMPT" -lt "$MAX_ATTEMPTS" && "$STATUS" != "completed" ]]; do
+            echo "Polling attempt #$((ATTEMPT + 1))"
+            ATTEMPT=$((ATTEMPT + 1))
+
+            response=$(curl -s \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer $GITHUB_TOKEN" \
+              "https://api.github.com/repos/cmsc430/assignments/actions/runs?branch=main&status=success&per_page=1")
+
+            if [[ "$(echo "$response" | jq '.total_count')" -gt 0 ]]; then
+              STATUS="completed"
+              run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
+              echo "RUN_ID=$run_id" >> $GITHUB_ENV
+            else
+              echo "Workflow not completed yet. Waiting for 2 minutes before next attempt."
+              sleep 120  # Wait for 2 minutes before polling again
+            fi
+          done
+
+          if [[ "$STATUS" != "completed" ]]; then
+            echo "Workflow did not complete in time. Exiting with failure."
+            exit 1
+          fi
+    - name: Download assignment zips
+      if: success()
+      env:
+        GITHUB_TOKEN: ${{ secrets.PAT_ZIPS_WORKFLOW }}
+      run: |
+          curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            https://api.github.com/repos/cmsc430/assignments/actions/runs/${{ env.RUN_ID }}/artifacts \
+            -o artifacts.zip
+    - name: Extract assignment zips
+      if: success()
+      run: |
+        unzip artifacts.zip
+        tar -xvf artifact.tar
+	mv knock-plus.zip www/main/
     - name: Archive www
       uses: actions/upload-pages-artifact@v3
       with:
